PRAGMA foreign_keys = ON;

CREATE TABLE users(
userid INTEGER PRIMARY KEY AUTOINCREMENT,
fullname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE sessions(
sessionid VARCHAR(36) PRIMARY KEY,
userid INTEGER NULL REFERENCES users(userid) ON DELETE CASCADE,
created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE conversations(
conversationid INTEGER PRIMARY KEY AUTOINCREMENT,
uuid VARCHAR(36) NOT NULL UNIQUE, 
sessionid VARCHAR(36) NULL REFERENCES sessions(sessionid) ON DELETE CASCADE,
userid INTEGER NULL REFERENCES users(userid) ON DELETE CASCADE,
title VARCHAR(255) NULL,
created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
CONSTRAINT chk_userid CHECK ((userid IS NOT NULL OR sessionid IS NOT NULL) AND NOT (userid IS NOT NULL AND sessionid IS NOT NULL))
);

CREATE TABLE messages (
messageid INTEGER PRIMARY KEY AUTOINCREMENT,
conversationid INTEGER NOT NULL REFERENCES conversations(conversationid) ON DELETE CASCADE,
role VARCHAR(20) NOT NULL, 
content TEXT NOT NULL,
created DATETIME DEFAULT CURRENT_TIMESTAMP
);